export const gearDamageTypesMaxtrix = {
  axes: ["ice", "fire", "poison", "physical"],
  bows: ["ice", "fire", "poison", "physical"],
  crossbows: ["ice", "fire", "poison", "physical"],
  daggers: ["ice", "fire", "poison", "physical"],
  hammers: ["ice", "fire", "poison", "physical"],
  shields: [],
  staves: [],
  swords: ["ice", "fire", "poison", "physical"],
};

export const weaponPerks = [
  "attack power",
  "criticals",
  "undead damage",
  "monster damage",
  "critter damage",
  "sorcerer damage",
  "elemental damage",
  "elite damage",
];

export const axePerks = ["throw distance", "throw damage", "explosions"];
export const bowPerks = ["shot distance", "slowing"];
export const crossbowPerks = ["slowing", "reload"];
export const daggerPerks = ["throw distance", "vampire", "poison"];
export const hammerPerks = ["throw distance", "slowing", "area damage"];
export const shieldPerks = ["knockback distance", "absorb"];
export const swordPerks = ["vampire", "throwable", "stab damage"];

export const gearPerksMatrix = {
  axes: [...axePerks, ...weaponPerks],
  bows: [...bowPerks, ...weaponPerks],
  crossbows: [...crossbowPerks, ...weaponPerks],
  daggers: [...daggerPerks, ...weaponPerks],
  hammers: [...hammerPerks, ...weaponPerks],
  shields: [...shieldPerks, ...weaponPerks],
  staves: [],
  swords: [...swordPerks, ...weaponPerks],
};

export const perkSet = new Set([
  ...weaponPerks,
  ...axePerks,
  ...bowPerks,
  ...crossbowPerks,
  ...daggerPerks,
  ...hammerPerks,
  ...shieldPerks,
  ...swordPerks,
]);

export const gearSlotPlacement = {
  axes: "hip",
  bows: "back",
  crossbows: "back",
  daggers: "hip",
  hammers: "hip",
  shields: "back",
  staves: "back",
  swords: "hip",
};

export const perkGearMatrix = Object.entries(gearPerksMatrix).reduce(
  (accumulator, item) => {
    const [gearName, perkNames] = item;
    const newStuff = perkNames.reduce((acc, perkname) => {
      acc[perkname] = gearName;
      return acc;
    }, {});
    for (const [g, ps] of Object.entries(newStuff)) {
      accumulator[g] = (accumulator[g] ?? []).concat(ps);
    }
    return accumulator;
  },
  {},
);

export const perkDescriptions = {
  "attack power": {
    description: "Increases damage by 5-30%",
    type: "weapons",
    "min chance": 1.0,
    "min multiplier": 1.05,
    "max chance": 1.0,
    "max multiplier": 1.3,
  },
  criticals: {
    description: "Gives 20-30% chance to critically strike for 300% damage",
    type: "weapons",
    "min chance": 0.2,
    "min multiplier": 3,
    "max chance": 0.3,
    "max multiplier": 3,
  },
  "undead damage": {
    description: "Increases damage by 5-30% to undead enemies",
    type: "weapons",
    "min chance": 1.0,
    "min multiplier": 1.05,
    "max chance": 1.0,
    "max multiplier": 1.3,
  },
  "monster damage": {
    description: "Increases damage by 5-30% to monsters",
    type: "weapons",
    "min chance": 1.0,
    "min multiplier": 1.05,
    "max chance": 1.0,
    "max multiplier": 1.3,
  },
  "critter damage": {
    description: "Increases damage by 5-30% to critters",
    type: "weapons",
    "min chance": 1.0,
    "min multiplier": 1.05,
    "max chance": 1.0,
    "max multiplier": 1.3,
  },
  "sorcerer damage": {
    description: "Increases damage by 5-30% to sorcerer enemies",
    type: "weapons",
    "min chance": 1.0,
    "min multiplier": 1.05,
    "max chance": 1.0,
    "max multiplier": 1.3,
  },
  "elemental damage": {
    description: "Increases damage by 5-30% to elemental enemies",
    type: "weapons",
    "min chance": 1.0,
    "min multiplier": 1.05,
    "max chance": 1.0,
    "max multiplier": 1.3,
  },
  "elite damage": {
    description: "Increases damage by 5-30% to elite enemies",
    type: "weapons",
    "min chance": 1.0,
    "min multiplier": 1.05,
    "max chance": 1.0,
    "max multiplier": 1.3,
  },
  "throw distance": {
    description: "Increases throwing range by 10-60%",
    type: "hammers",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
  },
  "throw damage": {
    description: "Increases throwing damage by 5-30%",
    type: "axes",
    "min chance": 1.0,
    "min multiplier": 1.05,
    "max chance": 1.0,
    "max multiplier": 1.3,
  },
  explosions: {
    description: "Gives 20-30% chance to explode for 200% damage",
    type: "axes",
    "min chance": 0.2,
    "min multiplier": 2,
    "max chance": 0.3,
    "max multiplier": 2,
  },
  slowing: {
    description: "Gives 20-30% chance to slow enemy",
    type: "hammers",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
  },
  reload: {
    description: "Gives 1-6 extra shots per reload",
    type: "crossbows",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
  },
  "shot distance": {
    description: "Increases shooting range by 10-60%",
    type: "bows",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
  },
  vampire: {
    description: "Gives 20-30% chance to heal 25% of player health",
    type: "swords",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
  },
  poison: {
    description: "Gives 20-30% chance to poison enemy",
    type: "daggers",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
  },
  "area damage": {
    description: "Gives 20-30% chance to explode for 200% damage",
    type: "hammers",
    "min chance": 0.2,
    "min multiplier": 2,
    "max chance": 0.3,
    "max multiplier": 2,
  },
  "knockback distance": {
    description: "Knockback distance increases shield knockback by 10-60%",
    type: "shields",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
  },
  absorb: {
    description: "Heals 4-25% of player health when blocking",
    type: "shields",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
  },
  throwable: {
    description: "Allows sword to be thrown",
    type: "swords",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
  },
  "stab damage": {
    description: "Increases damage by 50%",
    type: "swords",
    "min chance": 1.0,
    "min multiplier": 1.5,
    "max chance": 1.0,
    "max multiplier": 1.5,
  },
};

export const damageTypeDescriptions = {
  ice: "chance to freeze and cause embrittlement: frozen targets receive extra damage",
  fire: "chance to explode for 200% damage",
  poison: "chance to stun target for a few seconds",
  physical: "no additional effect",
};

export const exoDescriptions = {
  absorb: {
    description: "Decreases fall damage",
    level: 3,
    placement: "Legs",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  distance: {
    description: "Increase throwing distance",
    level: 4,
    placement: "Arms",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  blast: {
    description: "Reduces explosion damage taken",
    level: 5,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  endurance: {
    description: "Reduces slowdowns from poison and last chance",
    level: 6,
    placement: "Legs",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  mystify: {
    description: "Decreases ranged enemy accuracy",
    level: 7,
    placement: "Mind",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  pierce: {
    description: "Increase stabbing damage",
    level: 8,
    placement: "Arms",
    "min chance": 100 / 100,
    "min multiplier": 120 / 100,
    "max chance": 100 / 100,
    "max multiplier": 200 / 100,
    rank1: 120 / 100,
    rank2: 140 / 100,
    rank3: 160 / 100,
    rank4: 180 / 100,
    rank5: 200 / 100,
  },
  antidote: {
    description: "Decreases poison damage taken",
    level: 9,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  power: {
    description: "Increase Melee Damage",
    level: 10,
    placement: "Arms",
    "min chance": 100 / 100,
    "min multiplier": 110 / 100,
    "max chance": 100 / 100,
    "max multiplier": 150 / 100,
    rank1: 110 / 100,
    rank2: 120 / 100,
    rank3: 130 / 100,
    rank4: 140 / 100,
    rank5: 150 / 100,
  },
  leap: {
    description: "Increases movement speed in air",
    level: 12,
    placement: "Legs",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  grounded: {
    description: "Disables enemy jumping attacks",
    level: 13,
    placement: "Mind",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  dispel: {
    description: "Reduces magic damage taken",
    level: 14,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  heal: {
    description: "Increases potion health recovery",
    level: 15,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  vitality: {
    description: "Recover health every few seconds",
    level: 15,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  farshot: {
    description: "Increases bow/crossbow range",
    level: 16,
    placement: "Arms",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  armor: {
    description: "Reduces melee damage taken",
    level: 20,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  fortune: {
    description: "Increases gold reward at endgame by",
    level: 22,
    placement: "Mind",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  jump: {
    description: "Increases jump height",
    level: 24,
    placement: "Legs",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  might: {
    description: "Increases throwing damage",
    level: 26,
    placement: "Arms",
    "min chance": 100 / 100,
    "min multiplier": 120 / 100,
    "max chance": 100 / 100,
    "max multiplier": 200 / 100,
    rank1: 120 / 100,
    rank2: 140 / 100,
    rank3: 160 / 100,
    rank4: 180 / 100,
    rank5: 200 / 100,
  },
  knockback: {
    description: "Increases shield knockback",
    level: 28,
    placement: "Arms",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  haste: {
    description: "Increases movement speed",
    level: 30,
    placement: "Legs",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  ricochet: {
    description: "Reduces arrow damage taken",
    level: 32,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  pullback: {
    description: "Increases bow/crossbow damage",
    level: 34,
    placement: "Arms",
    "min chance": 100 / 100,
    "min multiplier": 110 / 100,
    "max chance": 100 / 100,
    "max multiplier": 150 / 100,
    rank1: 110 / 100,
    rank2: 120 / 100,
    rank3: 130 / 100,
    rank4: 140 / 100,
    rank5: 150 / 100,
  },
  stillness: {
    description: "Recover health every few seconds when not moving",
    level: 38,
    placement: "Mind",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  critical: {
    description: "Adds chance to increase melee damage",
    level: 40,
    placement: "Arms",
    "min chance": 0.2,
    "min multiplier": 140 / 100,
    "max chance": 0.4,
    "max multiplier": 300 / 100,
    rank1: 140 / 100,
    rank2: 180 / 100,
    rank3: 220 / 100,
    rank4: 260 / 100,
    rank5: 300 / 100,
  },
  resilience: {
    description: "Increases last stand time",
    level: 45,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  impale: {
    description: "Adds chance to increase bow/crossbow damage",
    level: 50,
    placement: "Arms",
    "min chance": 0.2,
    "min multiplier": 140 / 100,
    "max chance": 0.4,
    "max multiplier": 300 / 100,
    rank1: 140 / 100,
    rank2: 180 / 100,
    rank3: 220 / 100,
    rank4: 260 / 100,
    rank5: 300 / 100,
  },
};
