export const exoDescriptions = {
  absorb: {
    description: "Decreases fall damage",
    level: 3,
    placement: "Legs",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  distance: {
    description: "Increase throwing distance",
    level: 4,
    placement: "Arms",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  blast: {
    description: "Reduces explosion damage taken",
    level: 5,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  endurance: {
    description: "Reduces slowdowns from poison and last chance",
    level: 6,
    placement: "Legs",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  mystify: {
    description: "Decreases ranged enemy accuracy",
    level: 7,
    placement: "Mind",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  pierce: {
    description: "Increase stabbing damage",
    level: 8,
    placement: "Arms",
    "min chance": 100 / 100,
    "min multiplier": 120 / 100,
    "max chance": 100 / 100,
    "max multiplier": 200 / 100,
    rank1: 120 / 100,
    rank2: 140 / 100,
    rank3: 160 / 100,
    rank4: 180 / 100,
    rank5: 200 / 100,
    limitsEffectToAttackStyle: "stab",
  },
  antidote: {
    description: "Decreases poison damage taken",
    level: 9,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  power: {
    description: "Increase Melee Damage",
    level: 10,
    placement: "Arms",
    "min chance": 100 / 100,
    "min multiplier": 110 / 100,
    "max chance": 100 / 100,
    "max multiplier": 150 / 100,
    rank1: 110 / 100,
    rank2: 120 / 100,
    rank3: 130 / 100,
    rank4: 140 / 100,
    rank5: 150 / 100,
    limitsEffectToAttackStyle: "melee",
  },
  leap: {
    description: "Increases movement speed in air",
    level: 12,
    placement: "Legs",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  grounded: {
    description: "Disables enemy jumping attacks",
    level: 13,
    placement: "Mind",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  dispel: {
    description: "Reduces magic damage taken",
    level: 14,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  heal: {
    description: "Increases potion health recovery",
    level: 15,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  vitality: {
    description: "Recover health every few seconds",
    level: 15,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  farshot: {
    description: "Increases bow/crossbow range",
    level: 16,
    placement: "Arms",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  armor: {
    description: "Reduces melee damage taken",
    level: 20,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  fortune: {
    description: "Increases gold reward at endgame by",
    level: 22,
    placement: "Mind",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  jump: {
    description: "Increases jump height",
    level: 24,
    placement: "Legs",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  might: {
    description: "Increases throwing damage",
    level: 26,
    placement: "Arms",
    "min chance": 100 / 100,
    "min multiplier": 120 / 100,
    "max chance": 100 / 100,
    "max multiplier": 200 / 100,
    rank1: 120 / 100,
    rank2: 140 / 100,
    rank3: 160 / 100,
    rank4: 180 / 100,
    rank5: 200 / 100,
    limitsEffectToAttackStyle: "thrown",
  },
  knockback: {
    description: "Increases shield knockback",
    level: 28,
    placement: "Arms",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  haste: {
    description: "Increases movement speed",
    level: 30,
    placement: "Legs",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  ricochet: {
    description: "Reduces arrow damage taken",
    level: 32,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  pullback: {
    description: "Increases bow/crossbow damage",
    level: 34,
    placement: "Arms",
    "min chance": 100 / 100,
    "min multiplier": 110 / 100,
    "max chance": 100 / 100,
    "max multiplier": 150 / 100,
    rank1: 110 / 100,
    rank2: 120 / 100,
    rank3: 130 / 100,
    rank4: 140 / 100,
    rank5: 150 / 100,
    limitsEffectToAttackStyle: "arrow",
  },
  stillness: {
    description: "Recover health every few seconds when not moving",
    level: 38,
    placement: "Mind",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  critical: {
    description: "Adds chance to increase melee damage",
    level: 40,
    placement: "Arms",
    "min chance": 0.2,
    "min multiplier": 140 / 100,
    "max chance": 0.4,
    "max multiplier": 300 / 100,
    rank1: 140 / 100,
    rank2: 180 / 100,
    rank3: 220 / 100,
    rank4: 260 / 100,
    rank5: 300 / 100,
    limitsEffectToAttackStyle: "melee",
  },
  resilience: {
    description: "Increases last stand time",
    level: 45,
    placement: "Chest",
    "min chance": "",
    "min multiplier": "",
    "max chance": "",
    "max multiplier": "",
    rank1: "",
    rank2: "",
    rank3: "",
    rank4: "",
    rank5: "",
  },
  impale: {
    description: "Adds chance to increase bow/crossbow damage",
    level: 50,
    placement: "Arms",
    "min chance": 0.2,
    "min multiplier": 140 / 100,
    "max chance": 0.4,
    "max multiplier": 300 / 100,
    rank1: 140 / 100,
    rank2: 180 / 100,
    rank3: 220 / 100,
    rank4: 260 / 100,
    rank5: 300 / 100,
    limitsEffectToAttackStyle: "arrow",
  },
};
